#include "SharedConstants.h"

#include "Constant.h"
#include "Property.h"

namespace nonut::g2o
{
	void SharedConstants::init()
	{
		SQObject constTable = getConstTable();

#define GET_CONST(constName)                               \
	Property<Int> constName##Prop(#constName, constTable); \
	(constName) = constName##Prop.get()

		GET_CONST(UNRELIABLE);
		GET_CONST(UNRELIABLE_SEQUENCED);
		GET_CONST(RELIABLE);
		GET_CONST(RELIABLE_ORDERED);
		GET_CONST(RELIABLE_SEQUENCED);

		GET_CONST(DAMAGE_UNKNOWN);
		GET_CONST(DAMAGE_BARRIER);
		GET_CONST(DAMAGE_BLUNT);
		GET_CONST(DAMAGE_EDGE);
		GET_CONST(DAMAGE_FIRE);
		GET_CONST(DAMAGE_FLY);
		GET_CONST(DAMAGE_MAGIC);
		GET_CONST(DAMAGE_POINT);
		GET_CONST(DAMAGE_FALL);

		GET_CONST(CLIENT_SIDE);
		GET_CONST(SERVER_SIDE);

		GET_CONST(HAND_LEFT);
		GET_CONST(HAND_RIGHT);

		GET_CONST(WEAPON_1H);
		GET_CONST(WEAPON_2H);
		GET_CONST(WEAPON_BOW);
		GET_CONST(WEAPON_CBOW);

		GET_CONST(WEAPONMODE_NONE);
		GET_CONST(WEAPONMODE_FIST);
		GET_CONST(WEAPONMODE_DAG);
		GET_CONST(WEAPONMODE_1HS);
		GET_CONST(WEAPONMODE_2HS);
		GET_CONST(WEAPONMODE_BOW);
		GET_CONST(WEAPONMODE_CBOW);
		GET_CONST(WEAPONMODE_MAG);
		GET_CONST(WEAPONMODE_MAX);
	}
}
